#!/bin/bash

# Load all the basch scripts
if [ -f "/etc/solt/solt.conf" ]; then
    source /etc/solt/solt.conf
fi

# Update common folder
function _update_source_common {
    pushd $phabsource_dir/common
        git pull
    popd
}

# Update SolusSource Folder
function _update_source {
    _user_check
    pushd $phabsource_dir
        make clone -j$clone_jobs
        _show_info "Repo updated"
        make pull -j$clone_jobs
        _show_info "Packages updated"
    popd
}

# Search inside SolusSource folder
function _search_source {
    pushd $phabsource_dir
        ag --silent -QH $term ./*/$place
    popd
}

# Less verbose search of SolusSource folder
function _search_source_less {
    pushd $phabsource_dir
       ag --silent -Ql $term ./*/$place
    popd
}

# Remove deprecated packages
function _remove_source_pkg {
    pushd $phabsource_dir
        go run common/Go/deprecate_packages.go
    popd
}
    
# Get SolusSource repos modified in the last x days
function _source_last_modified {
    pushd $phabsource_dir
        ./common/Scripts/repos-modified-since-days.sh $days
    popd
}